### ISSUE TITLE
Possibility to do a language filter

### ISSUE THREAD

**Issue by suchoss** [marcusturewicz/dotnet-twitter-bot#33]
**Problem**
Currently when I am following .Net Bot - my twitter is cluttered with Chinese, Arabic and other to me unreadable tweets containing .NET string.

**Proposed solution**
I would like a possibility to follow only specific language mutations (CZ, EN)

Thanks

**Comment by marcusturewicz** [comment]
Hi @suchoss, I originally included all languages to make the bot as inclusive as possible, but I could see how this could be annoying. I can't think of a simple solution though, other than creating bots for each language which I don't really want to do. Any ideas?

**Comment by suchoss** [comment]
@marcusturewicz As you write - I don't see any other solution than creating bot/language which might be anoying (I understand). 

It would be easier if twitter could filter languages.

**Comment by marcusturewicz** [comment]
Closing this as I'd like to keep the bot inclusive.
