### ISSUE TITLE
Retweeted an Advert

### ISSUE THREAD

**Issue by skyhoshi** [marcusturewicz/dotnet-twitter-bot#5]
Miss on retweeting advert
https://twitter.com/CupidName/status/1245185624031801350

**Comment by marcusturewicz** [comment]
Thanks for the pick up. Any suggestions on how to remove these?

**Comment by skyhoshi** [comment]
I'll work on a Pull Request for a "Do Not Tweet if includes".
As for long term solution
My suggestion would be: 
1. To externalize the string sets. for your search terms as well as a "Do Not Retweet" Tweets, 
-- you could store a text file someplace as json an import that for each list. how to do it on AWS would require research for me. and load it each execution. there's some cost considerations there. 
2. Create a Mechanism for review of retweets, something that would DM you or an account with questionable content and upon response of "Yes" Or "No" the bot would ignore or retweet. 
3. you could use the DM Process as well to do management as well.

**Comment by skyhoshi** [comment]
found "Private Messages" https://github.com/linvi/tweetinvi/wiki/Messages
