### ISSUE TITLE
my twitter handle has "dotnet" and I don't like to be automatically retweeted

### ISSUE THREAD

**Issue by PaulPoinet** [marcusturewicz/dotnet-twitter-bot#8]
Hello, can you please make an exception for my twitter handle?
@paul_dotnet
https://twitter.com/paul_dotnet

**Comment by marcusturewicz** [comment]
Does this happen every time you tweet, or only when you're mentioned?

**Comment by PaulPoinet** [comment]
everytime I am mentioned...

**Comment by skyhoshi** [comment]
I think the best way to handle this is a Twitter list of users that can be cross referenced when the tweet is checked for retweeting. this will allow you to update the list without recompiling, and redeploying
keep the list updated with those that don't want to be retweeted (or tweeted too much) on the Bots account.

**Comment by marcusturewicz** [comment]
> I think the best way to handle this is a Twitter list of users that can be cross referenced when the tweet is checked for retweeting. this will allow you to update the list without recompiling, and redeploying
> keep the list updated with those that don't want to be retweeted (or tweeted too much) on the Bots account.

I like this approach, but it introduces complexity that I don't think we need yet. If the list starts to grow out of control then it will be a good time to handle all the exceptions with an externally updatable list. For now, adding @paul_dotnet to the exclusion list should suffice.
